name: Cross-Platform Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # macOS, Linux: Python & Meson
      - name: Set up Python (Unix-like systems)
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Meson and Ninja (Unix-like systems)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          pip install meson ninja

      - name: Configure Meson
        if: ${{ matrix.os != 'windows-latest' }}
        run: meson setup builddir --buildtype release

      - name: Build with Meson
        if: ${{ matrix.os != 'windows-latest' }}
        run: meson compile -C builddir

      # Windows: MSBuild
      - name: Generate buildDateTime.h
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $time = Get-Date -Format "HH:mm:ss"
          $content = "#define BUILD_DATE ${date}\n#define BUILD_TIME ${time}\n"
          Set-Content -Path DiscImageCreator\buildDateTime.h -Value $content -Encoding ascii
          Get-Content DiscImageCreator\buildDateTime.h

      - name: Set up MSBuild (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v2

      - name: Build with MSBuild
        if: ${{ matrix.os == 'windows-latest' }}
        #run: msbuild DiscImageCreator.sln /p:Configuration=Release_ANSI /p:Platform=x64
        run: msbuild DiscImageCreator.sln /p:Configuration=Release

      # Linux: MSBuild
      #- name: Set up MSBuild (Linux)
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  uses: microsoft/setup-msbuild@v2

      #- name: Build with MSBuild
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: msbuild DiscImageCreator_linux.sln /p:Configuration=Release /p:Platform=x64
