name: Manual Build DiscImageCreator (Meson)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Configure Meson
        run: meson setup builddir --buildtype release

      - name: Build with Meson
        run: meson compile -C builddir
